# NumPy

A biblioteca permite realizar operações matemáticas dos mais diversos tipos.

O que a torna tão importante é o fato de que a maioria das bibliotecas utilizadas em Data Science dependem dela.

In [1]:
import numpy as np

## 1. NumPy Arrays

### 1.1 Criando arrays a partir de listas.

É possível criar tanto **vetores** quanto **matrizes**.

In [3]:
lista = [1,2,3]
array = np.array(lista)

In [4]:
type(lista), type(array)

(list, numpy.ndarray)

In [5]:
array

array([1, 2, 3])

In [6]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 1.2 Outros métodos de gerar arrays

Na biblioteca NumPy existem vários métodos para criar arrays de acordo com a nossa necessidade.

#### arange

Retorna um array com valores **igualmente espaçados** num dado intervalo.

In [8]:
#gerando um array de 0 até 100 de 10 em 10
inicio = 0
fim = 101 #não é inclusivo!!
intervalo = 10 #a configuração default é 1

np.arange(inicio, fim, intervalo)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

#### linspace

Retorna um array com valores igualmente espaçados com intervalo e número de pontos definidos.

In [27]:
#array de 0 a 100 com 10 pontos
inicio = 0
fim = 100 #dessa vez é inclusivo
pontos = 10

np.linspace(inicio, fim, pontos)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

#### zeros, ones e eye

É possível gerar vetores e matrizes com todos os elementos nulos (zeros), iguais a um (ones) e a matriz identidade (eye).

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
#definindo o número de linhas e colunas de uma matriz
linhas = 3
colunas = 4

In [15]:
np.zeros((linhas,colunas))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((linhas,colunas))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
#matriz identidade 3x3 (3 linhas e 3 colunas)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 1.3 Random

Gerador de números aleatórios.

#### rand

Gera um array de dimensão dada composto de valores aleatórios entre 0 e 1

In [29]:
np.random.rand(5)

array([0.9974699 , 0.91346631, 0.46935868, 0.16018225, 0.95788258])

In [31]:
np.random.rand(3,4)

array([[0.64650034, 0.44860417, 0.53906558, 0.81432463],
       [0.54379328, 0.41859171, 0.63529829, 0.92248513],
       [0.00631479, 0.55720208, 0.75277918, 0.2538391 ]])

#### randn

Valores aleatórios provenientes de um distribuição normal.

In [32]:
np.random.randn(5)

array([-0.8142658 , -0.51176377,  0.59204922, -0.54219751,  1.50241837])

In [33]:
np.random.randn(2,3)

array([[ 0.76609612, -0.07328698,  0.72620025],
       [-0.84053613,  0.27558777,  0.39478632]])

#### randint

Gera um array com números inteiros num certo intervalo com quantidade definida.

In [36]:
inicio = 0
fim = 100 #exclusivo
quantidade = 5

np.random.randint(inicio, fim, quantidade)

array([32, 42, 50, 33,  2])

#### seed

Gera um 'random state' para que os números aleatórios permaneçam os mesmos depois de rodar o código novamente.

In [38]:
np.random.randint(0,100,10)

array([87, 99, 23,  2, 21, 52,  1, 87, 29, 37])

In [39]:
np.random.randint(0,100,10)

array([ 1, 63, 59, 20, 32, 75, 57, 21, 88, 48])

Como visto acima, os números aleatórios variam

In [37]:
np.random.seed(42) #escolher qual o 'random state' desejado
np.random.randint(0,100,10)

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [40]:
np.random.seed(42)
np.random.randint(0,100,10)

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

escolhendo o seed desejado, os números não variam mais!

### 1.4 Alguns atributos

Aqui veremos algumas funções úteis para manipular os arrays e obter suas características.

In [42]:
array = np.arange(0,24)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### reshape

Dado o array acima, com 24 componentes, podemos gerar uma matriz ao mudar sua dimensão.
A dimensão nova deve respeitar o número de componentes do array original. Por exemplo:

- 4 linhas e 6 colunas (4x6 = 24)
- 2 linhas e 12 colunas (2x12 = 24)

entre outras!

In [43]:
array.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [44]:
array.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

#### min, max, argmin e argmax
- min: valor mínimo no array
- max: valor máximo no array
- argmin: posição do mínimo (lembrando que as posições começam do 0 --> [0, 1, 2, ... ] )
- argmax: posição do máximo

In [51]:
np.random.seed(42) #escolhendo o seed
array = np.random.randint(0,100,8)
array

array([51, 92, 14, 71, 60, 20, 82, 86])

In [52]:
array.min()

14

In [53]:
array.max()

92

In [54]:
array.argmin()

2

In [55]:
array.argmax()

1

#### shape

Trata-se da dimensão de um array.

In [56]:
array = np.arange(0,24)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [58]:
array.shape #24 componentes apenas

(24,)

In [63]:
array.reshape(1,24) #1 linha e 24 colunas

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [64]:
array.reshape(1,24).shape

(1, 24)

In [67]:
array.reshape(6,4) #6 linhas e 4 colunas

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [68]:
array.reshape(6,4).shape

(6, 4)

### 1.5 Índices e seleção
#### Arrays
É possível selecionar valores de um array através de seu índice/posição, bem como um conjunto num certo intervalo.

In [73]:
array = np.arange(10,21,1)

In [74]:
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [75]:
array[6] #valor que está na posição 6

16

In [78]:
array[1:5] #valores das posições 1 até 4 (não inclui o 5)

array([11, 12, 13, 14])

In [81]:
#ainda é possível escolher o valor de uma certa posição:

array[8] = 0
array

array([10,  0,  0,  0, 14, 15, 16, 17,  0, 19, 20])

In [82]:
#também para um certo intervalo:
array[1:4] = 0
array

array([10,  0,  0,  0, 14, 15, 16, 17,  0, 19, 20])

#### Matrizes

Para **matrizes** basta apenas indicar a posição da linha e da coluna.

a notação pode ser tanto **[linha][coluna]** quanto **[linha, coluna]**.

In [83]:
matriz = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [101]:
matriz[0][1] #elemento da linha 0 e coluna 1

10

In [102]:
matriz[2] #selecionando a linha 2 inteira

array([35, 40, 45])

In [108]:
matriz[:2,1:] #selecionando um pedaço da matriz

array([[10, 15],
       [25, 30]])

#### Seleção condicional

É possível usar uma condição para selecionar os valores do array:

In [113]:
array = np.arange(10,21)

In [114]:
array > 13

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [115]:
array[array>13]

array([14, 15, 16, 17, 18, 19, 20])

In [117]:
array[array<13]

array([10, 11, 12])

## 2. Operações com NumPy

Operações matemáticas com os arrays:


### 2.1 Operações simples

In [121]:
array = np.arange(1,11)

In [122]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
array + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [125]:
array - 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
array*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [130]:
array/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [132]:
array**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [133]:
array + array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [134]:
array/array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [135]:
array**array

array([         1,          4,         27,        256,       3125,
            46656,     823543,   16777216,  387420489, 1410065408])

In [143]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
identidade = np.eye(3) #matriz identidade 3x3

In [144]:
matriz*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Para multiplicar matrizes, devemos usar a função matmul do numpy. Caso contrário, só haverá multiplicação entre os elementos de mesma linha e coluna.

A multiplicação entre uma matriz e a matriz identidade deve gerar a própria matriz:

In [140]:
np.matmul(matriz, identidade)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [145]:
matriz*identidade #a multiplicação simples não funciona aqui

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

### 2.2 Demais operações

Algumas das funções presentes no NumPy

In [147]:
np.sqrt(array) #retorna a raiz quadrada

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [148]:
np.exp(array) #retorna os exponenciais (e^número)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [150]:
np.sin(array) #retorna os senos

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [151]:
np.log(array) #retorna os logarítmos naturais

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

### 2.3 Estatísticas

In [152]:
array.sum() #soma dos valores

55

In [153]:
array.mean() #média dos valores

5.5

In [154]:
array.var() #variância

8.25

In [155]:
array.std() #desvio-padrão

2.8722813232690143